services:
  jupyterhub:
    build: .
    container_name: jupyterhub
    ports:
      - "8000:8000"
    volumes:
      - volume.tljh.jereiard:/home
      - /var/run/docker.sock:/var/run/docker.sock  # Add this line
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
volumes:
  volume.tljh.jereiard:
    external: true
